"""initial schema

Revision ID: 209254ebb0ba
Revises: 
Create Date: 2026-08-08 19:44:23.404931
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '209254ebb0ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('do_not_contact',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value_e164', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_do_not_contact'))
    )
    op.create_index(op.f('ix_do_not_contact_domain'), 'do_not_contact', ['domain'], unique=False)
    op.create_index(op.f('ix_do_not_contact_email'), 'do_not_contact', ['email'], unique=False)
    op.create_index(op.f('ix_do_not_contact_value_e164'), 'do_not_contact', ['value_e164'], unique=False)
    op.create_table('raw_fetches',
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('body_path', sa.Text(), nullable=True),
    sa.Column('body_bytes', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('url_hash', name=op.f('pk_raw_fetches'))
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategories', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('number_pref', sa.Text(), nullable=False),
    sa.Column('sources_enabled', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_leads', sa.Integer(), nullable=True),
    sa.Column('max_runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('subcategory', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('place_id', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.Text(), nullable=True),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('lead_score', sa.Integer(), nullable=True),
    sa.Column('merged_from', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_businesses_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses')),
    sa.UniqueConstraint('run_id', 'place_id', name='uq_businesses_run_id_place_id')
    )
    op.create_index('ix_businesses_name_norm', 'businesses', ['name_norm'], unique=False)
    op.create_index('ix_businesses_place_id', 'businesses', ['place_id'], unique=False)
    op.create_index('ix_businesses_run_id_lead_score', 'businesses', ['run_id', 'lead_score'], unique=False)
    op.create_table('source_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('consecutive_empty_reveals', sa.Integer(), nullable=False),
    sa.Column('requests_today', sa.Integer(), nullable=False),
    sa.Column('paused_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_source_state_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_state'))
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=False),
    sa.Column('value_e164', sa.Text(), nullable=True),
    sa.Column('line_type', sa.Text(), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('wa_evidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('wa_label', sa.Text(), nullable=True),
    sa.Column('person_name', sa.Text(), nullable=True),
    sa.Column('person_role', sa.Text(), nullable=True),
    sa.Column('attribution', sa.Text(), nullable=True),
    sa.Column('belongs_to', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_contacts_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index('ix_contacts_business_id_rank', 'contacts', ['business_id', 'rank'], unique=False)
    op.create_index('ix_contacts_value_e164', 'contacts', ['value_e164'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_value_e164', table_name='contacts')
    op.drop_index('ix_contacts_business_id_rank', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('source_state')
    op.drop_index('ix_businesses_run_id_lead_score', table_name='businesses')
    op.drop_index('ix_businesses_place_id', table_name='businesses')
    op.drop_index('ix_businesses_name_norm', table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('runs')
    op.drop_table('raw_fetches')
    op.drop_index(op.f('ix_do_not_contact_value_e164'), table_name='do_not_contact')
    op.drop_index(op.f('ix_do_not_contact_email'), table_name='do_not_contact')
    op.drop_index(op.f('ix_do_not_contact_domain'), table_name='do_not_contact')
    op.drop_table('do_not_contact')
    # ### end Alembic commands ###
