"""contacts.wa_evidence_url

Revision ID: 9aacb52b7301
Revises: 209254ebb0ba
Create Date: 2026-08-08 22:52:40.875156
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9aacb52b7301'
down_revision: str | None = '209254ebb0ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('wa_evidence_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'wa_evidence_url')
    # ### end Alembic commands ###
